name: Review PR
on:
  workflow_run:
    workflows:
      - Review-Trigger
    types:
      - completed

permissions:
  contents: read
  checks: write



jobs:
  review-approvals:
    runs-on: ubuntu-latest
    environment: TESTING
    steps:
      - name: Extract content of artifact
        id: number
        uses: Bullrich/extract-text-from-artifact@main
        with:
          artifact-name: pr_number
      - name: Generate token
        id: team_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REVIEW_APP_ID }}
          private_key: ${{ secrets.REVIEW_APP_KEY }}
      # !This must always point to main. 
      # Change it for the PRs but remember to change it back
      - name: "Evaluates PR reviews and assigns reviewers"
        uses: paritytech/review-bot@test-branch
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          team-token: ${{ steps.team_token.outputs.token }}
          checks-token: ${{ steps.team_token.outputs.token }}
          pr-number: ${{ steps.number.outputs.content }}
